CREATE TABLE USUARIO(ID INT PRIMARY KEY AUTO_INCREMENT, USERNAME VARCHAR(25) NOT NULL UNIQUE , PASSWORD VARCHAR(25) NOT NULL, NOMBRE VARCHAR(25), APELLIDO VARCHAR(25), FECHA_NACIMIENTO DATE, FOTO_USUARIO VARCHAR(200));

CREATE TABLE TWEET(ID INT PRIMARY KEY AUTO_INCREMENT, CONTENIDO VARCHAR(200), FECHA_CREACION DATE, IS_PUBLIC BOOLEAN, IMAGEN VARCHAR(200), ID_USUARIO INT, FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID));

CREATE TABLE HASHTAG(ID INT PRIMARY KEY AUTO_INCREMENT, NOMBRE VARCHAR(200));

CREATE TABLE USUARIO_HASHTAG(HASHTAG_ID INT, USUARIO_ID INT, FOREIGN KEY(HASHTAG_ID) REFERENCES HASHTAG(ID), FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID),
PRIMARY KEY(HASHTAG_ID,USUARIO_ID));

CREATE TABLE TWEET_HASHTAG(HASHTAG_ID INT, TWEET_ID INT, FOREIGN KEY(HASHTAG_ID) REFERENCES HASHTAG(ID), FOREIGN KEY(TWEET_ID) REFERENCES TWEET(ID), PRIMARY KEY(HASHTAG_ID,TWEET_ID));

CREATE TABLE USUARIO_SEGUIDOR(USUARIO_ID INT, SEGUIDOR_ID INT, FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID), FOREIGN KEY(SEGUIDOR_ID) REFERENCES USUARIO(ID));