//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestCiguaClient.CiguaWSReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/")]
    public partial class FileNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/")]
    public partial class tweet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contenidoField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private usuario idUsuarioField;
        
        private string imagenField;
        
        private bool isPublicField;
        
        private bool isPublicFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("contenido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public usuario idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("imagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool isPublic {
            get {
                return this.isPublicField;
            }
            set {
                this.isPublicField = value;
                this.RaisePropertyChanged("isPublic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPublicSpecified {
            get {
                return this.isPublicFieldSpecified;
            }
            set {
                this.isPublicFieldSpecified = value;
                this.RaisePropertyChanged("isPublicSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private string fotoUsuarioField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fotoUsuario {
            get {
                return this.fotoUsuarioField;
            }
            set {
                this.fotoUsuarioField = value;
                this.RaisePropertyChanged("fotoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", ConfigurationName="CiguaWSReference.CiguaWS")]
    public interface CiguaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getImageRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getImageResponse getImage(RestCiguaClient.CiguaWSReference.getImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getImageRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getImageResponse")]
        System.IAsyncResult BegingetImage(RestCiguaClient.CiguaWSReference.getImageRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getImageResponse EndgetImage(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getUserResponse getUser(RestCiguaClient.CiguaWSReference.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserResponse")]
        System.IAsyncResult BegingetUser(RestCiguaClient.CiguaWSReference.getUserRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getUserResponse EndgetUser(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/authenticateUserRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/authenticateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.authenticateUserResponse authenticateUser(RestCiguaClient.CiguaWSReference.authenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/authenticateUserRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/authenticateUserResponse")]
        System.IAsyncResult BeginauthenticateUser(RestCiguaClient.CiguaWSReference.authenticateUserRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.authenticateUserResponse EndauthenticateUser(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getTweetsByUserRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getTweetsByUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getTweetsByUserResponse getTweetsByUser(RestCiguaClient.CiguaWSReference.getTweetsByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getTweetsByUserRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getTweetsByUserResponse")]
        System.IAsyncResult BegingetTweetsByUser(RestCiguaClient.CiguaWSReference.getTweetsByUserRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getTweetsByUserResponse EndgetTweetsByUser(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/crearTweetRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/crearTweetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RestCiguaClient.CiguaWSReference.FileNotFoundException), Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/crearTweet/Fault/FileNotFoundExc" +
            "eption", Name="FileNotFoundException")]
        [System.ServiceModel.FaultContractAttribute(typeof(RestCiguaClient.CiguaWSReference.IOException), Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/crearTweet/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.crearTweetResponse crearTweet(RestCiguaClient.CiguaWSReference.crearTweetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/crearTweetRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/crearTweetResponse")]
        System.IAsyncResult BegincrearTweet(RestCiguaClient.CiguaWSReference.crearTweetRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.crearTweetResponse EndcrearTweet(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserByTweetIdRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserByTweetIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getUserByTweetIdResponse getUserByTweetId(RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserByTweetIdRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getUserByTweetIdResponse")]
        System.IAsyncResult BegingetUserByTweetId(RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getUserByTweetIdResponse EndgetUserByTweetId(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getCantTweetsRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getCantTweetsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getCantTweetsResponse getCantTweets(RestCiguaClient.CiguaWSReference.getCantTweetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getCantTweetsRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getCantTweetsResponse")]
        System.IAsyncResult BegingetCantTweets(RestCiguaClient.CiguaWSReference.getCantTweetsRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getCantTweetsResponse EndgetCantTweets(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowingCountRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowingCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getFollowingCountResponse getFollowingCount(RestCiguaClient.CiguaWSReference.getFollowingCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowingCountRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowingCountResponse")]
        System.IAsyncResult BegingetFollowingCount(RestCiguaClient.CiguaWSReference.getFollowingCountRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getFollowingCountResponse EndgetFollowingCount(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowersCountRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowersCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RestCiguaClient.CiguaWSReference.getFollowersCountResponse getFollowersCount(RestCiguaClient.CiguaWSReference.getFollowersCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowersCountRequest", ReplyAction="http://webservices.parcial2.pw.pucmm.edu/CiguaWS/getFollowersCountResponse")]
        System.IAsyncResult BegingetFollowersCount(RestCiguaClient.CiguaWSReference.getFollowersCountRequest request, System.AsyncCallback callback, object asyncState);
        
        RestCiguaClient.CiguaWSReference.getFollowersCountResponse EndgetFollowersCount(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImage", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageRoute;
        
        public getImageRequest() {
        }
        
        public getImageRequest(string imageRoute) {
            this.imageRoute = imageRoute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImageResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getImageResponse() {
        }
        
        public getImageResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public getUserRequest() {
        }
        
        public getUserRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RestCiguaClient.CiguaWSReference.usuario @return;
        
        public getUserResponse() {
        }
        
        public getUserResponse(RestCiguaClient.CiguaWSReference.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateUser", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class authenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public authenticateUserRequest() {
        }
        
        public authenticateUserRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateUserResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class authenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public authenticateUserResponse() {
        }
        
        public authenticateUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTweetsByUser", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getTweetsByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public getTweetsByUserRequest() {
        }
        
        public getTweetsByUserRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTweetsByUserResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getTweetsByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RestCiguaClient.CiguaWSReference.tweet[] @return;
        
        public getTweetsByUserResponse() {
        }
        
        public getTweetsByUserResponse(RestCiguaClient.CiguaWSReference.tweet[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearTweet", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class crearTweetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contenido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imagenNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] imagen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isPublic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public crearTweetRequest() {
        }
        
        public crearTweetRequest(string contenido, string imagenNombre, byte[] imagen, bool isPublic, string username) {
            this.contenido = contenido;
            this.imagenNombre = imagenNombre;
            this.imagen = imagen;
            this.isPublic = isPublic;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearTweetResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class crearTweetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public crearTweetResponse() {
        }
        
        public crearTweetResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByTweetId", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getUserByTweetIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tweetId;
        
        public getUserByTweetIdRequest() {
        }
        
        public getUserByTweetIdRequest(int tweetId) {
            this.tweetId = tweetId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByTweetIdResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getUserByTweetIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RestCiguaClient.CiguaWSReference.usuario @return;
        
        public getUserByTweetIdResponse() {
        }
        
        public getUserByTweetIdResponse(RestCiguaClient.CiguaWSReference.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCantTweets", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getCantTweetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public getCantTweetsRequest() {
        }
        
        public getCantTweetsRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCantTweetsResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getCantTweetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public getCantTweetsResponse() {
        }
        
        public getCantTweetsResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFollowingCount", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getFollowingCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public getFollowingCountRequest() {
        }
        
        public getFollowingCountRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFollowingCountResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getFollowingCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public getFollowingCountResponse() {
        }
        
        public getFollowingCountResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFollowersCount", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getFollowersCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public getFollowersCountRequest() {
        }
        
        public getFollowersCountRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFollowersCountResponse", WrapperNamespace="http://webservices.parcial2.pw.pucmm.edu/", IsWrapped=true)]
    public partial class getFollowersCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.parcial2.pw.pucmm.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public getFollowersCountResponse() {
        }
        
        public getFollowersCountResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CiguaWSChannel : RestCiguaClient.CiguaWSReference.CiguaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RestCiguaClient.CiguaWSReference.usuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RestCiguaClient.CiguaWSReference.usuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public authenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTweetsByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTweetsByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RestCiguaClient.CiguaWSReference.tweet[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RestCiguaClient.CiguaWSReference.tweet[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class crearTweetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public crearTweetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getUserByTweetIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getUserByTweetIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RestCiguaClient.CiguaWSReference.usuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RestCiguaClient.CiguaWSReference.usuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCantTweetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCantTweetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFollowingCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFollowingCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFollowersCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFollowersCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CiguaWSClient : System.ServiceModel.ClientBase<RestCiguaClient.CiguaWSReference.CiguaWS>, RestCiguaClient.CiguaWSReference.CiguaWS {
        
        private BeginOperationDelegate onBegingetImageDelegate;
        
        private EndOperationDelegate onEndgetImageDelegate;
        
        private System.Threading.SendOrPostCallback ongetImageCompletedDelegate;
        
        private BeginOperationDelegate onBegingetUserDelegate;
        
        private EndOperationDelegate onEndgetUserDelegate;
        
        private System.Threading.SendOrPostCallback ongetUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginauthenticateUserDelegate;
        
        private EndOperationDelegate onEndauthenticateUserDelegate;
        
        private System.Threading.SendOrPostCallback onauthenticateUserCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTweetsByUserDelegate;
        
        private EndOperationDelegate onEndgetTweetsByUserDelegate;
        
        private System.Threading.SendOrPostCallback ongetTweetsByUserCompletedDelegate;
        
        private BeginOperationDelegate onBegincrearTweetDelegate;
        
        private EndOperationDelegate onEndcrearTweetDelegate;
        
        private System.Threading.SendOrPostCallback oncrearTweetCompletedDelegate;
        
        private BeginOperationDelegate onBegingetUserByTweetIdDelegate;
        
        private EndOperationDelegate onEndgetUserByTweetIdDelegate;
        
        private System.Threading.SendOrPostCallback ongetUserByTweetIdCompletedDelegate;
        
        private BeginOperationDelegate onBegingetCantTweetsDelegate;
        
        private EndOperationDelegate onEndgetCantTweetsDelegate;
        
        private System.Threading.SendOrPostCallback ongetCantTweetsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetFollowingCountDelegate;
        
        private EndOperationDelegate onEndgetFollowingCountDelegate;
        
        private System.Threading.SendOrPostCallback ongetFollowingCountCompletedDelegate;
        
        private BeginOperationDelegate onBegingetFollowersCountDelegate;
        
        private EndOperationDelegate onEndgetFollowersCountDelegate;
        
        private System.Threading.SendOrPostCallback ongetFollowersCountCompletedDelegate;
        
        public CiguaWSClient() {
        }
        
        public CiguaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CiguaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CiguaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CiguaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getImageCompletedEventArgs> getImageCompleted;
        
        public event System.EventHandler<getUserCompletedEventArgs> getUserCompleted;
        
        public event System.EventHandler<authenticateUserCompletedEventArgs> authenticateUserCompleted;
        
        public event System.EventHandler<getTweetsByUserCompletedEventArgs> getTweetsByUserCompleted;
        
        public event System.EventHandler<crearTweetCompletedEventArgs> crearTweetCompleted;
        
        public event System.EventHandler<getUserByTweetIdCompletedEventArgs> getUserByTweetIdCompleted;
        
        public event System.EventHandler<getCantTweetsCompletedEventArgs> getCantTweetsCompleted;
        
        public event System.EventHandler<getFollowingCountCompletedEventArgs> getFollowingCountCompleted;
        
        public event System.EventHandler<getFollowersCountCompletedEventArgs> getFollowersCountCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getImageResponse RestCiguaClient.CiguaWSReference.CiguaWS.getImage(RestCiguaClient.CiguaWSReference.getImageRequest request) {
            return base.Channel.getImage(request);
        }
        
        public byte[] getImage(string imageRoute) {
            RestCiguaClient.CiguaWSReference.getImageRequest inValue = new RestCiguaClient.CiguaWSReference.getImageRequest();
            inValue.imageRoute = imageRoute;
            RestCiguaClient.CiguaWSReference.getImageResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getImage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetImage(RestCiguaClient.CiguaWSReference.getImageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetImage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetImage(string imageRoute, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getImageRequest inValue = new RestCiguaClient.CiguaWSReference.getImageRequest();
            inValue.imageRoute = imageRoute;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetImage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getImageResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetImage(System.IAsyncResult result) {
            return base.Channel.EndgetImage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public byte[] EndgetImage(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getImageResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetImage(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string imageRoute = ((string)(inValues[0]));
            return this.BegingetImage(imageRoute, callback, asyncState);
        }
        
        private object[] OnEndgetImage(System.IAsyncResult result) {
            byte[] retVal = this.EndgetImage(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetImageCompleted(object state) {
            if ((this.getImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getImageCompleted(this, new getImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getImageAsync(string imageRoute) {
            this.getImageAsync(imageRoute, null);
        }
        
        public void getImageAsync(string imageRoute, object userState) {
            if ((this.onBegingetImageDelegate == null)) {
                this.onBegingetImageDelegate = new BeginOperationDelegate(this.OnBegingetImage);
            }
            if ((this.onEndgetImageDelegate == null)) {
                this.onEndgetImageDelegate = new EndOperationDelegate(this.OnEndgetImage);
            }
            if ((this.ongetImageCompletedDelegate == null)) {
                this.ongetImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetImageCompleted);
            }
            base.InvokeAsync(this.onBegingetImageDelegate, new object[] {
                        imageRoute}, this.onEndgetImageDelegate, this.ongetImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getUserResponse RestCiguaClient.CiguaWSReference.CiguaWS.getUser(RestCiguaClient.CiguaWSReference.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public RestCiguaClient.CiguaWSReference.usuario getUser(string username) {
            RestCiguaClient.CiguaWSReference.getUserRequest inValue = new RestCiguaClient.CiguaWSReference.getUserRequest();
            inValue.username = username;
            RestCiguaClient.CiguaWSReference.getUserResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetUser(RestCiguaClient.CiguaWSReference.getUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetUser(string username, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getUserRequest inValue = new RestCiguaClient.CiguaWSReference.getUserRequest();
            inValue.username = username;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getUserResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetUser(System.IAsyncResult result) {
            return base.Channel.EndgetUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RestCiguaClient.CiguaWSReference.usuario EndgetUser(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getUserResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetUser(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BegingetUser(username, callback, asyncState);
        }
        
        private object[] OnEndgetUser(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.usuario retVal = this.EndgetUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetUserCompleted(object state) {
            if ((this.getUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getUserCompleted(this, new getUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getUserAsync(string username) {
            this.getUserAsync(username, null);
        }
        
        public void getUserAsync(string username, object userState) {
            if ((this.onBegingetUserDelegate == null)) {
                this.onBegingetUserDelegate = new BeginOperationDelegate(this.OnBegingetUser);
            }
            if ((this.onEndgetUserDelegate == null)) {
                this.onEndgetUserDelegate = new EndOperationDelegate(this.OnEndgetUser);
            }
            if ((this.ongetUserCompletedDelegate == null)) {
                this.ongetUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetUserCompleted);
            }
            base.InvokeAsync(this.onBegingetUserDelegate, new object[] {
                        username}, this.onEndgetUserDelegate, this.ongetUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.authenticateUserResponse RestCiguaClient.CiguaWSReference.CiguaWS.authenticateUser(RestCiguaClient.CiguaWSReference.authenticateUserRequest request) {
            return base.Channel.authenticateUser(request);
        }
        
        public bool authenticateUser(string username, string password) {
            RestCiguaClient.CiguaWSReference.authenticateUserRequest inValue = new RestCiguaClient.CiguaWSReference.authenticateUserRequest();
            inValue.username = username;
            inValue.password = password;
            RestCiguaClient.CiguaWSReference.authenticateUserResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).authenticateUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BeginauthenticateUser(RestCiguaClient.CiguaWSReference.authenticateUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginauthenticateUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginauthenticateUser(string username, string password, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.authenticateUserRequest inValue = new RestCiguaClient.CiguaWSReference.authenticateUserRequest();
            inValue.username = username;
            inValue.password = password;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BeginauthenticateUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.authenticateUserResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndauthenticateUser(System.IAsyncResult result) {
            return base.Channel.EndauthenticateUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndauthenticateUser(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.authenticateUserResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndauthenticateUser(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginauthenticateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginauthenticateUser(username, password, callback, asyncState);
        }
        
        private object[] OnEndauthenticateUser(System.IAsyncResult result) {
            bool retVal = this.EndauthenticateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnauthenticateUserCompleted(object state) {
            if ((this.authenticateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.authenticateUserCompleted(this, new authenticateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void authenticateUserAsync(string username, string password) {
            this.authenticateUserAsync(username, password, null);
        }
        
        public void authenticateUserAsync(string username, string password, object userState) {
            if ((this.onBeginauthenticateUserDelegate == null)) {
                this.onBeginauthenticateUserDelegate = new BeginOperationDelegate(this.OnBeginauthenticateUser);
            }
            if ((this.onEndauthenticateUserDelegate == null)) {
                this.onEndauthenticateUserDelegate = new EndOperationDelegate(this.OnEndauthenticateUser);
            }
            if ((this.onauthenticateUserCompletedDelegate == null)) {
                this.onauthenticateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnauthenticateUserCompleted);
            }
            base.InvokeAsync(this.onBeginauthenticateUserDelegate, new object[] {
                        username,
                        password}, this.onEndauthenticateUserDelegate, this.onauthenticateUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getTweetsByUserResponse RestCiguaClient.CiguaWSReference.CiguaWS.getTweetsByUser(RestCiguaClient.CiguaWSReference.getTweetsByUserRequest request) {
            return base.Channel.getTweetsByUser(request);
        }
        
        public RestCiguaClient.CiguaWSReference.tweet[] getTweetsByUser(string username) {
            RestCiguaClient.CiguaWSReference.getTweetsByUserRequest inValue = new RestCiguaClient.CiguaWSReference.getTweetsByUserRequest();
            inValue.username = username;
            RestCiguaClient.CiguaWSReference.getTweetsByUserResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getTweetsByUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetTweetsByUser(RestCiguaClient.CiguaWSReference.getTweetsByUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTweetsByUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetTweetsByUser(string username, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getTweetsByUserRequest inValue = new RestCiguaClient.CiguaWSReference.getTweetsByUserRequest();
            inValue.username = username;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetTweetsByUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getTweetsByUserResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetTweetsByUser(System.IAsyncResult result) {
            return base.Channel.EndgetTweetsByUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RestCiguaClient.CiguaWSReference.tweet[] EndgetTweetsByUser(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getTweetsByUserResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetTweetsByUser(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetTweetsByUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BegingetTweetsByUser(username, callback, asyncState);
        }
        
        private object[] OnEndgetTweetsByUser(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.tweet[] retVal = this.EndgetTweetsByUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTweetsByUserCompleted(object state) {
            if ((this.getTweetsByUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTweetsByUserCompleted(this, new getTweetsByUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTweetsByUserAsync(string username) {
            this.getTweetsByUserAsync(username, null);
        }
        
        public void getTweetsByUserAsync(string username, object userState) {
            if ((this.onBegingetTweetsByUserDelegate == null)) {
                this.onBegingetTweetsByUserDelegate = new BeginOperationDelegate(this.OnBegingetTweetsByUser);
            }
            if ((this.onEndgetTweetsByUserDelegate == null)) {
                this.onEndgetTweetsByUserDelegate = new EndOperationDelegate(this.OnEndgetTweetsByUser);
            }
            if ((this.ongetTweetsByUserCompletedDelegate == null)) {
                this.ongetTweetsByUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTweetsByUserCompleted);
            }
            base.InvokeAsync(this.onBegingetTweetsByUserDelegate, new object[] {
                        username}, this.onEndgetTweetsByUserDelegate, this.ongetTweetsByUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.crearTweetResponse RestCiguaClient.CiguaWSReference.CiguaWS.crearTweet(RestCiguaClient.CiguaWSReference.crearTweetRequest request) {
            return base.Channel.crearTweet(request);
        }
        
        public bool crearTweet(string contenido, string imagenNombre, byte[] imagen, bool isPublic, string username) {
            RestCiguaClient.CiguaWSReference.crearTweetRequest inValue = new RestCiguaClient.CiguaWSReference.crearTweetRequest();
            inValue.contenido = contenido;
            inValue.imagenNombre = imagenNombre;
            inValue.imagen = imagen;
            inValue.isPublic = isPublic;
            inValue.username = username;
            RestCiguaClient.CiguaWSReference.crearTweetResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).crearTweet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegincrearTweet(RestCiguaClient.CiguaWSReference.crearTweetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincrearTweet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegincrearTweet(string contenido, string imagenNombre, byte[] imagen, bool isPublic, string username, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.crearTweetRequest inValue = new RestCiguaClient.CiguaWSReference.crearTweetRequest();
            inValue.contenido = contenido;
            inValue.imagenNombre = imagenNombre;
            inValue.imagen = imagen;
            inValue.isPublic = isPublic;
            inValue.username = username;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegincrearTweet(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.crearTweetResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndcrearTweet(System.IAsyncResult result) {
            return base.Channel.EndcrearTweet(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndcrearTweet(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.crearTweetResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndcrearTweet(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegincrearTweet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string contenido = ((string)(inValues[0]));
            string imagenNombre = ((string)(inValues[1]));
            byte[] imagen = ((byte[])(inValues[2]));
            bool isPublic = ((bool)(inValues[3]));
            string username = ((string)(inValues[4]));
            return this.BegincrearTweet(contenido, imagenNombre, imagen, isPublic, username, callback, asyncState);
        }
        
        private object[] OnEndcrearTweet(System.IAsyncResult result) {
            bool retVal = this.EndcrearTweet(result);
            return new object[] {
                    retVal};
        }
        
        private void OncrearTweetCompleted(object state) {
            if ((this.crearTweetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.crearTweetCompleted(this, new crearTweetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void crearTweetAsync(string contenido, string imagenNombre, byte[] imagen, bool isPublic, string username) {
            this.crearTweetAsync(contenido, imagenNombre, imagen, isPublic, username, null);
        }
        
        public void crearTweetAsync(string contenido, string imagenNombre, byte[] imagen, bool isPublic, string username, object userState) {
            if ((this.onBegincrearTweetDelegate == null)) {
                this.onBegincrearTweetDelegate = new BeginOperationDelegate(this.OnBegincrearTweet);
            }
            if ((this.onEndcrearTweetDelegate == null)) {
                this.onEndcrearTweetDelegate = new EndOperationDelegate(this.OnEndcrearTweet);
            }
            if ((this.oncrearTweetCompletedDelegate == null)) {
                this.oncrearTweetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncrearTweetCompleted);
            }
            base.InvokeAsync(this.onBegincrearTweetDelegate, new object[] {
                        contenido,
                        imagenNombre,
                        imagen,
                        isPublic,
                        username}, this.onEndcrearTweetDelegate, this.oncrearTweetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getUserByTweetIdResponse RestCiguaClient.CiguaWSReference.CiguaWS.getUserByTweetId(RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest request) {
            return base.Channel.getUserByTweetId(request);
        }
        
        public RestCiguaClient.CiguaWSReference.usuario getUserByTweetId(int tweetId) {
            RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest inValue = new RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest();
            inValue.tweetId = tweetId;
            RestCiguaClient.CiguaWSReference.getUserByTweetIdResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getUserByTweetId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetUserByTweetId(RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetUserByTweetId(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetUserByTweetId(int tweetId, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest inValue = new RestCiguaClient.CiguaWSReference.getUserByTweetIdRequest();
            inValue.tweetId = tweetId;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetUserByTweetId(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getUserByTweetIdResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetUserByTweetId(System.IAsyncResult result) {
            return base.Channel.EndgetUserByTweetId(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RestCiguaClient.CiguaWSReference.usuario EndgetUserByTweetId(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getUserByTweetIdResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetUserByTweetId(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetUserByTweetId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int tweetId = ((int)(inValues[0]));
            return this.BegingetUserByTweetId(tweetId, callback, asyncState);
        }
        
        private object[] OnEndgetUserByTweetId(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.usuario retVal = this.EndgetUserByTweetId(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetUserByTweetIdCompleted(object state) {
            if ((this.getUserByTweetIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getUserByTweetIdCompleted(this, new getUserByTweetIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getUserByTweetIdAsync(int tweetId) {
            this.getUserByTweetIdAsync(tweetId, null);
        }
        
        public void getUserByTweetIdAsync(int tweetId, object userState) {
            if ((this.onBegingetUserByTweetIdDelegate == null)) {
                this.onBegingetUserByTweetIdDelegate = new BeginOperationDelegate(this.OnBegingetUserByTweetId);
            }
            if ((this.onEndgetUserByTweetIdDelegate == null)) {
                this.onEndgetUserByTweetIdDelegate = new EndOperationDelegate(this.OnEndgetUserByTweetId);
            }
            if ((this.ongetUserByTweetIdCompletedDelegate == null)) {
                this.ongetUserByTweetIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetUserByTweetIdCompleted);
            }
            base.InvokeAsync(this.onBegingetUserByTweetIdDelegate, new object[] {
                        tweetId}, this.onEndgetUserByTweetIdDelegate, this.ongetUserByTweetIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getCantTweetsResponse RestCiguaClient.CiguaWSReference.CiguaWS.getCantTweets(RestCiguaClient.CiguaWSReference.getCantTweetsRequest request) {
            return base.Channel.getCantTweets(request);
        }
        
        public long getCantTweets(string username) {
            RestCiguaClient.CiguaWSReference.getCantTweetsRequest inValue = new RestCiguaClient.CiguaWSReference.getCantTweetsRequest();
            inValue.username = username;
            RestCiguaClient.CiguaWSReference.getCantTweetsResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getCantTweets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetCantTweets(RestCiguaClient.CiguaWSReference.getCantTweetsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCantTweets(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetCantTweets(string username, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getCantTweetsRequest inValue = new RestCiguaClient.CiguaWSReference.getCantTweetsRequest();
            inValue.username = username;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetCantTweets(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getCantTweetsResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetCantTweets(System.IAsyncResult result) {
            return base.Channel.EndgetCantTweets(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public long EndgetCantTweets(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getCantTweetsResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetCantTweets(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetCantTweets(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BegingetCantTweets(username, callback, asyncState);
        }
        
        private object[] OnEndgetCantTweets(System.IAsyncResult result) {
            long retVal = this.EndgetCantTweets(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCantTweetsCompleted(object state) {
            if ((this.getCantTweetsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCantTweetsCompleted(this, new getCantTweetsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCantTweetsAsync(string username) {
            this.getCantTweetsAsync(username, null);
        }
        
        public void getCantTweetsAsync(string username, object userState) {
            if ((this.onBegingetCantTweetsDelegate == null)) {
                this.onBegingetCantTweetsDelegate = new BeginOperationDelegate(this.OnBegingetCantTweets);
            }
            if ((this.onEndgetCantTweetsDelegate == null)) {
                this.onEndgetCantTweetsDelegate = new EndOperationDelegate(this.OnEndgetCantTweets);
            }
            if ((this.ongetCantTweetsCompletedDelegate == null)) {
                this.ongetCantTweetsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCantTweetsCompleted);
            }
            base.InvokeAsync(this.onBegingetCantTweetsDelegate, new object[] {
                        username}, this.onEndgetCantTweetsDelegate, this.ongetCantTweetsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getFollowingCountResponse RestCiguaClient.CiguaWSReference.CiguaWS.getFollowingCount(RestCiguaClient.CiguaWSReference.getFollowingCountRequest request) {
            return base.Channel.getFollowingCount(request);
        }
        
        public long getFollowingCount(string username) {
            RestCiguaClient.CiguaWSReference.getFollowingCountRequest inValue = new RestCiguaClient.CiguaWSReference.getFollowingCountRequest();
            inValue.username = username;
            RestCiguaClient.CiguaWSReference.getFollowingCountResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getFollowingCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetFollowingCount(RestCiguaClient.CiguaWSReference.getFollowingCountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFollowingCount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetFollowingCount(string username, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getFollowingCountRequest inValue = new RestCiguaClient.CiguaWSReference.getFollowingCountRequest();
            inValue.username = username;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetFollowingCount(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getFollowingCountResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetFollowingCount(System.IAsyncResult result) {
            return base.Channel.EndgetFollowingCount(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public long EndgetFollowingCount(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getFollowingCountResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetFollowingCount(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetFollowingCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BegingetFollowingCount(username, callback, asyncState);
        }
        
        private object[] OnEndgetFollowingCount(System.IAsyncResult result) {
            long retVal = this.EndgetFollowingCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFollowingCountCompleted(object state) {
            if ((this.getFollowingCountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFollowingCountCompleted(this, new getFollowingCountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFollowingCountAsync(string username) {
            this.getFollowingCountAsync(username, null);
        }
        
        public void getFollowingCountAsync(string username, object userState) {
            if ((this.onBegingetFollowingCountDelegate == null)) {
                this.onBegingetFollowingCountDelegate = new BeginOperationDelegate(this.OnBegingetFollowingCount);
            }
            if ((this.onEndgetFollowingCountDelegate == null)) {
                this.onEndgetFollowingCountDelegate = new EndOperationDelegate(this.OnEndgetFollowingCount);
            }
            if ((this.ongetFollowingCountCompletedDelegate == null)) {
                this.ongetFollowingCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFollowingCountCompleted);
            }
            base.InvokeAsync(this.onBegingetFollowingCountDelegate, new object[] {
                        username}, this.onEndgetFollowingCountDelegate, this.ongetFollowingCountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getFollowersCountResponse RestCiguaClient.CiguaWSReference.CiguaWS.getFollowersCount(RestCiguaClient.CiguaWSReference.getFollowersCountRequest request) {
            return base.Channel.getFollowersCount(request);
        }
        
        public long getFollowersCount(string username) {
            RestCiguaClient.CiguaWSReference.getFollowersCountRequest inValue = new RestCiguaClient.CiguaWSReference.getFollowersCountRequest();
            inValue.username = username;
            RestCiguaClient.CiguaWSReference.getFollowersCountResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).getFollowersCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestCiguaClient.CiguaWSReference.CiguaWS.BegingetFollowersCount(RestCiguaClient.CiguaWSReference.getFollowersCountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFollowersCount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetFollowersCount(string username, System.AsyncCallback callback, object asyncState) {
            RestCiguaClient.CiguaWSReference.getFollowersCountRequest inValue = new RestCiguaClient.CiguaWSReference.getFollowersCountRequest();
            inValue.username = username;
            return ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).BegingetFollowersCount(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestCiguaClient.CiguaWSReference.getFollowersCountResponse RestCiguaClient.CiguaWSReference.CiguaWS.EndgetFollowersCount(System.IAsyncResult result) {
            return base.Channel.EndgetFollowersCount(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public long EndgetFollowersCount(System.IAsyncResult result) {
            RestCiguaClient.CiguaWSReference.getFollowersCountResponse retVal = ((RestCiguaClient.CiguaWSReference.CiguaWS)(this)).EndgetFollowersCount(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetFollowersCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BegingetFollowersCount(username, callback, asyncState);
        }
        
        private object[] OnEndgetFollowersCount(System.IAsyncResult result) {
            long retVal = this.EndgetFollowersCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFollowersCountCompleted(object state) {
            if ((this.getFollowersCountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFollowersCountCompleted(this, new getFollowersCountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFollowersCountAsync(string username) {
            this.getFollowersCountAsync(username, null);
        }
        
        public void getFollowersCountAsync(string username, object userState) {
            if ((this.onBegingetFollowersCountDelegate == null)) {
                this.onBegingetFollowersCountDelegate = new BeginOperationDelegate(this.OnBegingetFollowersCount);
            }
            if ((this.onEndgetFollowersCountDelegate == null)) {
                this.onEndgetFollowersCountDelegate = new EndOperationDelegate(this.OnEndgetFollowersCount);
            }
            if ((this.ongetFollowersCountCompletedDelegate == null)) {
                this.ongetFollowersCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFollowersCountCompleted);
            }
            base.InvokeAsync(this.onBegingetFollowersCountDelegate, new object[] {
                        username}, this.onEndgetFollowersCountDelegate, this.ongetFollowersCountCompletedDelegate, userState);
        }
    }
}
